export const TRANSLATIONS = {
  dashboard: 'ড্যাশবোর্ড',
  openingStock: 'ওপেনিং স্টক',
  receive: 'পণ্য গ্রহণ',
  sales: 'বিক্রয়',
  distribution: 'বিতরণ',
  returns: 'ফেরৎ',
  outletSales: 'আউটলেট থেকে বিক্রয়',
  reconciliation: 'স্টক মিলকরণ',
  damage: 'ড্যামেজ',
  free: 'ফ্রি',
  reports: 'রিপোর্ট',
  editTransactions: 'এন্ট্রি এডিট/মুছুন',
  products: 'পণ্য তালিকা',
  outlets: 'আউটলেট তালিকা',
  addProduct: 'নতুন পণ্য যোগ করুন',
  addOutlet: 'নতুন আউটলেট যোগ করুন',
  totalStock: 'মোট বর্তমান স্টক',
  todaySales: 'আজকের বিক্রয়',
  monthlySales: 'মাসিক বিক্রয়',
  lowStockAlert: 'স্টক কম (সতর্কতা)',
  date: 'তারিখ',
  productName: 'পণ্যের নাম',
  quantity: 'পরিমাণ',
  unit: 'ইউনিট',
  note: 'নোট',
  invoiceNumber: 'ইনভয়েস নম্বর',
  supplier: 'সরবরাহকারী/কোম্পানি',
  customerName: 'ক্রেতার নাম',
  price: 'মূল্য',
  paymentType: 'পেমেন্ট টাইপ',
  cash: 'নগদ',
  due: 'বাকি',
  availableStock: 'উপলব্ধ স্টক',
  save: 'সংরক্ষণ করুন',
  cancel: 'বাতিল',
  add: 'যোগ করুন',
  edit: 'সম্পাদনা',
  delete: 'মুছে ফেলুন',
  noData: 'কোন তথ্য পাওয়া যায়নি',
  stockReport: 'স্টক রিপোর্ট',
  receiveReport: 'রিসিভ রিপোর্ট',
  salesReport: 'সেলস রিপোর্ট',
  carton: 'শলাকা',
  packet: 'পিচ',
};
